## This is a tutorial temp file
1) uv venv
2) uv pip install ipykernel
3) uv pip install -r requirements.txt
4) To activate the env:  .venv\Scripts\activate

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Q1
print(pd.__version__)

3.0.5

In [3]:
#Q2
data='car_fuel_efficiency_2026.csv'
df=pd.read_csv(data)
print("length or count:",len(df))
df.head()

length or count: 10000

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
#Q3
print(df.columns)
len(df.fuel_type)
df.fuel_type.unique()

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [5]:
#Q4
print("Null columns:",df.columns[df.isnull().sum()>0])
df.isnull().sum()

Null columns: Index(['horsepower', 'acceleration'], dtype='str')

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [6]:
#Q5
df[df.origin=="Asia"].describe()
print('Max fuel efficiency of Asian cars:', df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max())

Max fuel efficiency of Asian cars: 41.2

In [7]:
#Q6
df.horsepower.describe()
df_median=df.horsepower.median()
df_mode=df.horsepower.mode()[0]
print("Previous median and mode:", df_median,df_mode)
df['horsepower'] = df['horsepower'].fillna(df_mode)
print("New horsepower median:",df.horsepower.median())

Previous median and mode: 254.0 252.0
New horsepower median: 252.0

In [8]:
print(df[df['horsepower'].isnull()])

Empty DataFrame
Columns: [model_year, origin, fuel_type, drivetrain, num_doors, engine_displacement, num_cylinders, horsepower, vehicle_weight, acceleration, fuel_efficiency_mpg]
Index: []

In [9]:
#Q7
df.head()
df1=df[df['origin']=='Asia']
df1_sub=df1[['vehicle_weight', 'model_year']].head(7)
X=df1_sub.to_numpy()
XTX=X.T.dot(X)
XTX_inv=np.linalg.inv(XTX)
Y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
W=XTX_inv.dot(X.T).dot(Y) #multiplication of inverse, transpose, and Y
result=W.sum()
print(result)

0.36919696904925486

In [10]:
df1_sub

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [11]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [ ]:
#trials
df.groupby('fuel_type').fuel_efficiency_mpg.max()

fuel_type
Diesel      41.2
Gasoline    38.5
Hybrid      39.8
Name: fuel_efficiency_mpg, dtype: float64