## This is a tutorial temp file
1) uv venv
2) uv pip install ipykernel
3) uv pip install -r requirements.txt
4) To activate the env:  .venv\Scripts\activate

In [1]:
import pandas as pd
import numpy as np

In [ ]:
#Q1
print(pd.__version__)

3.0.5

In [64]:
#Q2
data='car_fuel_efficiency_2026.csv'
df=pd.read_csv(data)
print("length or count:",len(df))
df.head()

length or count: 10000

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [ ]:
#Q3
print(df.columns)
len(df.fuel_type)
df.fuel_type.unique()

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [ ]:
#Q4
print("Null columns:",df.columns[df.isnull().sum()>0])
df.isnull().sum()

Null columns: Index(['horsepower', 'acceleration'], dtype='str')

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [97]:
#Q5
df[df.origin=="Asia"].describe()
print('Max fuel efficiency of Asian cars:', df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max())

Max fuel efficiency of Asian cars: 41.2

In [67]:
#Q6
df.horsepower.describe()
df_median=df.horsepower.median()
df_mode=df.horsepower.mode()[0]
print("Previous median and mode:", df_median,df_mode)
df['horsepower'] = df['horsepower'].fillna(df_mode)
print("New horsepower median:",df.horsepower.median())

Previous median and mode: 254.0 252.0
New horsepower median: 252.0

In [66]:
print(df[df['horsepower'].isnull()])

      model_year  origin fuel_type         drivetrain  num_doors  \
10          1978    Asia  Gasoline    All-wheel drive          3
12          1983     USA    Diesel  Front-wheel drive          3
32          1978     USA  Gasoline   Rear-wheel drive          3
39          1994    Asia  Gasoline  Front-wheel drive          3
46          1983  Europe  Gasoline   Rear-wheel drive          4
...          ...     ...       ...                ...        ...
9955        1984    Asia  Gasoline   Rear-wheel drive          2
9957        1984    Asia  Gasoline  Front-wheel drive          4
9963        1982    Asia    Hybrid  Front-wheel drive          4
9980        1977     USA    Hybrid  Front-wheel drive          5
9986        1984  Europe  Gasoline  Front-wheel drive          3

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
10                   2410              6         NaN            4420
12                   2370              7         NaN            4390
32                   2080              6         NaN            4350
39                   2390              6         NaN            4300
46                   2130              6         NaN            4360
...                   ...            ...         ...             ...
9955                 2290              6         NaN            4330
9957                 2170              5         NaN            4020
9963                 2450              7         NaN            4470
9980                 2390              6         NaN            4550
9986                 2330              6         NaN            4110

      acceleration  fuel_efficiency_mpg
10            19.5                 26.8
12            20.7                 30.4
32            16.8                 24.1
39            18.2                 33.5
46            20.9                 29.7
...            ...                  ...
9955          19.3                 26.8
9957          18.3                 30.2
9963          16.6                 27.8
9980          19.8                 32.0
9986          19.2                 29.6

[877 rows x 11 columns]

In [93]:
#Q7
df.head()
df1=df[df['origin']=='Asia']
df1_sub=df1[['vehicle_weight', 'model_year']].head(7)
X=df1_sub.to_numpy()
XTX=X.T.dot(X)
XTX_inv=np.linalg.inv(XTX)
Y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
W=XTX_inv.dot(X.T).dot(Y) #multiplication of inverse, transpose, and Y
result=W.sum()
print(result)

0.36919696904925486

In [92]:
df1_sub

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019